name: 'codeql-field-queries'
description: 'Advanced Security Field CodeQL Queries'

inputs:

  token:
    default: ${{ github.token }}
  instance:
    default: https://github.com
  bundle-repository:
    default: GeekMasher/codeql-queries

outputs:
  tools:
    description: URL to the latest field bundle (tools)

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        GITHUB_TOKEN=${{ inputs.token }}
        CODEQL_BUNDLE_VERSION=$(gh release list --repo ${{ inputs.bundle-repository }} -L 1 | awk '{split($0,a,"\t"); print a[3]}')
        echo "::set-output name=tools::${{ inputs.instance }}/${{ inputs.bundle-repository }}/releases/download/${CODEQL_BUNDLE_VERSION}/customized-codeql-bundle.tar.gz"
