name: 'codeql-field-queries'
description: 'Advanced Security Field CodeQL Queries'

inputs:

  token:
    default: ${{ github.token }}
  instance:
    default: github.com
  instance-api:
    default: api.github.com
  bundle-repository:
    default: GeekMasher/codeql-queries

outputs:
  tools:
    description: URL to the latest field bundle (tools)

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        CODEQL_BUNDLE_VERSION=$(curl --silent "https://${{ inputs.instance-api }}/repos/${{ inputs.bundle-repository }}/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
        echo "::set-output name=tools::https://${{ inputs.instance }}/${{ inputs.bundle-repository }}/releases/download/${CODEQL_BUNDLE_VERSION}/customized-codeql-bundle.tar.gz"
