using System;
using System.IO;
using System.Text;
using System.Runtime.Serialization;
using System.Security.Cryptography;
using System.Security.Permissions;

public class StaticSalt {
  public void Test1() {
    string password = "TestPassword";

    // BAD: Static String 
    var salt = Encoding.UTF8.GetBytes("Hardcoded Salt");
    var hash = new Rfc2898DeriveBytes(password, salt);

    // Good: Randomly generated byte array 
    var randonSalt = new byte[16];
    RandomNumberGenerator.Create().GetBytes(randonSalt);
    var hash_safe = new Rfc2898DeriveBytes(password, randonSalt);
  }

  public static string generateSalt() {
    return "Hardcoded Salt2";
  }
  public void Test2() {
    string password = "TestPassword2";

    // BAD: Static String 
    var salt = Encoding.UTF8.GetBytes(StaticSalt.generateSalt());
    var hash = new Rfc2898DeriveBytes(password, salt);
  }
}